#!/bin/sh

# # Originaly,This script does the following:
# #	Run by itself, set the wallpaper (at X start).
# #	If given a file, set that as the new wallpaper.
# #	If given a directory, choose random file in it.
# #	If wal is installed, also generate a colorscheme.
#
# # Location of link to wallpaper link.
# bgloc="${XDG_CACHE_HOME:-$HOME/.cache/}/bg"
#
# [ -f "$1" ] && ln -sf "$(readlink -f "$1")" "$bgloc" && notify-send -i "$bgloc" "Changing wallpaper..."
#
# [ -d "$1" ] && ln -sf "$(find "$(readlink -f "$1")" -iregex '.*.\(jpg\|jpeg\|png\|gif\)' -type f | shuf -n 1)" "$bgloc" && notify-send -i "$bgloc" "Random Wallpaper chosen."
#
# # If pywal is installed, use it.
# # https://adamrutter.github.io/pywal-themes-preview/
# #wal -s -i "$(readlink -f "$bgloc")" --saturate 0.5 -o "${XDG_CONFIG_HOME:-$HOME/.config}/wal/postrun" >/dev/null 2>&1
# wal -s -i "$(readlink -f "$bgloc")" --theme ashes --saturate 1.0 -o "${XDG_CONFIG_HOME:-$HOME/.config}/wal/postrun" >/dev/null 2>&1
#
# xwallpaper --zoom "$bgloc"
# wal --theme ashes
# #xwallpaper --stretch "$bgloc"

feh --bg-scale ~/Pictures/render_4k_512_noise-modified.png
wallust run ~/Pictures/render_4k_512_noise-modified.png
